# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Run and Test

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build and Generate coverage
      run: mvn test jacoco:report
      
    - name: run Sender
      run: mvn compile exec:java -Dexec.mainClass="Sender.Sender"
      
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./target/site/jacoco
        retention-days: 21

    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.c*
      
    - name: run
      run: ./testchecker

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21
        
    - name: Build Sender and Receiver Packages
      run:  mvn -B package --file pom.xml -Dmaven.test.skip=true
    - name: Pipe sender to 
      run: ./bmssender | java -jar target/ReceiverService.jar
